workflows:
  ios-build:
    name: Build iOS for TestFlight
    max_build_duration: 60

    environment:
      node: 20.11.1
      xcode: latest
      cocoapods: default
      vars:
        APP_NAME: "VesselApp"
        APP_STORE_CONNECT_ISSUER_ID: Environ("APP_STORE_CONNECT_ISSUER_ID")
        APP_STORE_CONNECT_KEY_IDENTIFIER: Environ("APP_STORE_CONNECT_KEY_IDENTIFIER")
        APP_STORE_CONNECT_PRIVATE_KEY: Environ("APP_STORE_CONNECT_PRIVATE_KEY")

    scripts:
      - name: Install dependencies
        script: |
          echo "📦 Installing npm dependencies..."
          npm ci

          echo "📦 Installing Capacitor iOS platform..."
          npm install @capacitor/ios --force

          echo "🔧 Syncing iOS platform..."
          npx cap sync ios

          echo "📁 Installing CocoaPods dependencies..."
          cd ios/App
          pod install
          cd ../..

      - name: Build and export .ipa
        script: |
          echo "🚀 Building and exporting iOS release..."
          cd ios/App

          # 1️⃣ Архивируем приложение
          xcodebuild -workspace App.xcworkspace \
                     -scheme App \
                     -sdk iphoneos \
                     -configuration Release \
                     -archivePath ../build/App.xcarchive \
                     clean archive

          # 2️⃣ Экспортируем ipa-файл
          xcodebuild -exportArchive \
                     -archivePath ../build/App.xcarchive \
                     -exportPath ../build/Release-iphoneos \
                     -exportOptionsPlist ExportOptions.plist || true

          cd ../..

    artifacts:
      - ios/App/build/Release-iphoneos/*.ipa
      - ios/App/build/Release-iphoneos/*.app
      - ios/build/App.xcarchive/**/*

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
