workflows:
  ios-build:
    name: Build iOS for TestFlight
    max_build_duration: 60
    environment:
      node: 20.11.1
      xcode: latest
      cocoapods: default
      vars:
        APP_NAME: "VesselApp"

    scripts:
      - name: Install dependencies
        script: |
          echo "📦 Installing npm dependencies..."
          npm ci
          echo "📦 Installing Capacitor iOS platform..."
          npm install @capacitor/ios --force
          echo "🔧 Fixing permissions..."
          chmod +x ./node_modules/.bin/cap || true
          echo "🔄 Syncing iOS platform..."
          npx cap sync ios
          echo "📁 Installing CocoaPods dependencies..."
          cd ios
          pod install
          cd ..

      - name: Build iOS app
        script: |
          echo "🚀 Building iOS release..."
          cd ios
          xcodebuild -workspace App.xcworkspace \
                     -scheme App \
                     -sdk iphoneos \
                     -configuration Release \
                     clean build \
                     CODE_SIGN_IDENTITY="" \
                     CODE_SIGNING_REQUIRED=NO \
                     CODE_SIGNING_ALLOWED=NO

    artifacts:
      - ios/build/**/*.ipa
      - ios/build/**/*.app

    publishing:
      email:
        recipients:
          - bobylevvlad0310@icloud.com
