workflows:
  ios-build:
    name: Build iOS for TestFlight
    max_build_duration: 60

    integrations:
      app_store_connect: mykey  # Имя интеграции в Codemagic

    environment:
      node: 20.11.1
      xcode: latest
      cocoapods: default
      vars:
        APP_NAME: "VesselApp"
        DEVELOPMENT_TEAM: "AJ5RPURRUV"
        BUNDLE_ID: "vesseldatabase.app"

    scripts:
      - name: Install dependencies
        script: |
          echo "📦 Installing npm dependencies..."
          npm ci

          echo "📦 Installing Capacitor iOS platform..."
          npm install @capacitor/ios --force

          echo "🔧 Syncing iOS platform..."
          npx cap sync ios

          echo "📁 Installing CocoaPods dependencies..."
          cd ios/App
          pod install
          cd ../..

      - name: Build and export .ipa
        script: |
          echo "🚀 Building and exporting iOS release with automatic signing..."
          cd ios/App
          mkdir -p ../build

          # Очистка DerivedData перед сборкой
          rm -rf ~/Library/Developer/Xcode/DerivedData

          # 🏗️ Сборка и архивирование
          xcodebuild -workspace App.xcworkspace \
                     -scheme App \
                     -sdk iphoneos \
                     -configuration Release \
                     -archivePath ../build/App.xcarchive \
                     DEVELOPMENT_TEAM=$DEVELOPMENT_TEAM \
                     PRODUCT_BUNDLE_IDENTIFIER=$BUNDLE_ID \
                     CODE_SIGN_STYLE=Automatic \
                     -allowProvisioningUpdates \
                     clean archive || exit 1

          # 📦 Экспорт .ipa для App Store
          xcodebuild -exportArchive \
                     -archivePath ../build/App.xcarchive \
                     -exportPath ../build \
                     -exportOptionsPlist ExportOptions.plist \
                     -allowProvisioningUpdates || exit 1

          echo "📂 Checking build folder content:"
          find ../build -type f -print
          cd ../..

    artifacts:
      - ios/build/*.ipa
      - ios/build/**/*.ipa
      - ios/App/build/*.ipa
      - ios/App/build/**/*.ipa
      - ios/build/App.xcarchive/**/*

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
