workflows:
  ios-build:
    name: Build iOS for TestFlight
    max_build_duration: 60
    environment:
      vars:
        APP_NAME: "VesselApp"
      node: 20.11.1
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm ci
          chmod +x ./node_modules/.bin/cap || true
          npx cap sync ios
      - name: Build iOS app
        script: |
          cd ios
          xcodebuild -workspace App.xcworkspace \
                     -scheme App \
                     -sdk iphoneos \
                     -configuration Release \
                     clean build \
                     CODE_SIGN_IDENTITY="" \
                     CODE_SIGNING_REQUIRED=NO \
                     CODE_SIGNING_ALLOWED=NO
    artifacts:
      - ios/build/**/*.ipa
      - ios/build/**/*.app
    publishing:
      email:
        recipients:
          - bobylevvlad0310@icloud.com
