workflows:
  ios-build:
    name: Build iOS for TestFlight
    max_build_duration: 60

    integrations:
      app_store_connect: mykey

    environment:
      node: 20.11.1
      xcode: latest
      cocoapods: default
      vars:
        APP_NAME: "VesselApp"
        DEVELOPMENT_TEAM: "AJ5RPURRUV"
        BUNDLE_ID: "vesseldatabase.app"

    automatic_code_signing:
      apple_team_id: "AJ5RPURRUV"
      bundle_identifier: "vesseldatabase.app"
      provisioning_profile_name: "VesselApp_Distribution"
      certificate_key: "VesselDatabase12"

    scripts:
      - name: Install dependencies
        script: |
          echo "📦 Installing npm dependencies..."
          npm ci
          npm install @capacitor/ios --force
          npx cap sync ios
          cd ios/App
          pod install
          cd ../..

      - name: Build and export .ipa
        script: |
          echo "🚀 Building iOS release..."
          cd ios/App
          mkdir -p ../build
          rm -rf ~/Library/Developer/Xcode/DerivedData

          xcodebuild -workspace App.xcworkspace \
                     -scheme App \
                     -sdk iphoneos \
                     -configuration Release \
                     -archivePath ../build/App.xcarchive \
                     DEVELOPMENT_TEAM=$DEVELOPMENT_TEAM \
                     PRODUCT_BUNDLE_IDENTIFIER=$BUNDLE_ID \
                     CODE_SIGN_STYLE=Automatic \
                     -allowProvisioningUpdates \
                     clean archive || exit 1

          xcodebuild -exportArchive \
                     -archivePath ../build/App.xcarchive \
                     -exportPath ../build \
                     -exportOptionsPlist ExportOptions.plist \
                     -allowProvisioningUpdates || exit 1

          cd ../..
          echo "✅ Build complete"

    artifacts:
      - ios/build/**/*.ipa
      - ios/App/build/**/*.ipa
      - ios/build/App.xcarchive/**/*

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
