workflows:
  ios-build:
    name: Build iOS for TestFlight
    max_build_duration: 60

    integrations:
      app_store_connect: mykey

    environment:
      node: 20.11.1
      xcode: latest
      cocoapods: default
      vars:
        APP_NAME: "VesselApp"
        DEVELOPMENT_TEAM: "AJ5RPURRUV"
        BUNDLE_ID: "vesseldatabase.app"
        PROVISIONING_PROFILE_SPECIFIER: "VesselApp_Distribution"
        CODE_SIGN_IDENTITY: "Apple Distribution"

    scripts:
      - name: Install dependencies
        script: |
          echo "📦 Installing npm dependencies..."
          npm ci
          npm install @capacitor/ios --force
          npx cap sync ios
          cd ios/App
          pod install
          cd ../..

      - name: Build and export .ipa
        script: |
          echo "🚀 Building iOS release..."
          cd ios/App
          mkdir -p ../build
          rm -rf ~/Library/Developer/Xcode/DerivedData

          echo "🔧 Archiving with manual signing..."
          xcodebuild -workspace App.xcworkspace \
                     -scheme App \
                     -sdk iphoneos \
                     -configuration Release \
                     -archivePath ../build/App.xcarchive \
                     DEVELOPMENT_TEAM=$DEVELOPMENT_TEAM \
                     PRODUCT_BUNDLE_IDENTIFIER=$BUNDLE_ID \
                     CODE_SIGN_STYLE=Manual \
                     CODE_SIGN_IDENTITY="$CODE_SIGN_IDENTITY" \
                     PROVISIONING_PROFILE_SPECIFIER="$PROVISIONING_PROFILE_SPECIFIER" \
                     -allowProvisioningUpdates \
                     clean archive || exit 1

          echo "📦 Exporting .ipa..."
          xcodebuild -exportArchive \
                     -archivePath ../build/App.xcarchive \
                     -exportPath ../build \
                     -exportOptionsPlist ExportOptions.plist \
                     -allowProvisioningUpdates || exit 1

          cd ../..
          echo "✅ Build complete"

    artifacts:
      - ios/build/**/*.ipa
      - ios/App/build/**/*.ipa
      - ios/build/App.xcarchive/**/*

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
