workflows:
  ios-build:
    name: Build iOS for TestFlight
    max_build_duration: 60

    environment:
      node: 20.11.1
      xcode: latest
      cocoapods: default
      vars:
        APP_NAME: "VesselApp"
        APP_STORE_CONNECT_ISSUER_ID: Environ("APP_STORE_CONNECT_ISSUER_ID")
        APP_STORE_CONNECT_KEY_IDENTIFIER: Environ("APP_STORE_CONNECT_KEY_IDENTIFIER")
        APP_STORE_CONNECT_PRIVATE_KEY: Environ("APP_STORE_CONNECT_PRIVATE_KEY")
        DEVELOPMENT_TEAM: "AJ5RPURRUV"  # ← твой Team ID

    code_signing:
      xcode:
        use_automatic_signing: true
        apple_team_id: "AJ5RPURRUV"     # ← тот же Team ID
        bundle_identifier: "vesseldatabase.app"
        app_store_connect_issuer_id: Environ("APP_STORE_CONNECT_ISSUER_ID")
        app_store_connect_key_identifier: Environ("APP_STORE_CONNECT_KEY_IDENTIFIER")
        app_store_connect_private_key: Environ("APP_STORE_CONNECT_PRIVATE_KEY")

    scripts:
      - name: Install dependencies
        script: |
          echo "📦 Installing npm dependencies..."
          npm ci

          echo "📦 Installing Capacitor iOS platform..."
          npm install @capacitor/ios --force

          echo "🔧 Syncing iOS platform..."
          npx cap sync ios

          echo "📁 Installing CocoaPods dependencies..."
          cd ios/App
          pod install
          cd ../..

      - name: Build and export .ipa
        script: |
          echo "🚀 Building and exporting iOS release..."
          cd ios/App

          mkdir -p ../build

          echo "🔧 Archiving app (allowing provisioning updates)..."
          xcodebuild -workspace App.xcworkspace \
                     -scheme App \
                     -sdk iphoneos \
                     -configuration Release \
                     -archivePath ../build/App.xcarchive \
                     DEVELOPMENT_TEAM=$DEVELOPMENT_TEAM \
                     -allowProvisioningUpdates \
                     clean archive || exit 1

          echo "📦 Exporting .ipa..."
          xcodebuild -exportArchive \
                     -archivePath ../build/App.xcarchive \
                     -exportOptionsPlist ExportOptions.plist \
                     -exportPath ../build \
                     -allowProvisioningUpdates || exit 1

          echo "📂 Checking build folder content:"
          find ../build -type f -print

          cd ../..

    artifacts:
      - ios/build/*.ipa
      - ios/build/**/*.ipa
      - ios/App/build/*.ipa
      - ios/App/build/**/*.ipa
      - ios/build/App.xcarchive/**/*

    publishing:
      app_store_connect:
        api_key: Environ("APP_STORE_CONNECT_PRIVATE_KEY")
        key_id: Environ("APP_STORE_CONNECT_KEY_IDENTIFIER")
        issuer_id: Environ("APP_STORE_CONNECT_ISSUER_ID")
        submit_to_testflight: true
