workflows:
  ios-build:
    name: Build iOS for TestFlight
    max_build_duration: 60

    integrations:
      app_store_connect: mykey  # ✅ твоя интеграция Apple Developer Portal

    environment:
      node: 20.11.1
      xcode: latest
      cocoapods: default
      vars:
        DEVELOPMENT_TEAM: "AJ5RPURRUV"
        BUNDLE_ID: "vesseldatabase.app"

    scripts:
      - name: 📦 Install dependencies
        script: |
          echo "Installing dependencies..."
          npm ci
          npm install @capacitor/ios --force
          npx cap sync ios
          cd ios/App && pod install && cd ../..
          echo "✅ Dependencies installed"

      - name: 🧱 Build (archive)
        script: |
          echo "🚀 Building iOS app..."
          cd ios/App
          rm -rf ~/Library/Developer/Xcode/DerivedData
          xcodebuild -workspace App.xcworkspace \
                     -scheme App \
                     -sdk iphoneos \
                     -configuration Release \
                     -archivePath ../build/App.xcarchive \
                     DEVELOPMENT_TEAM=$DEVELOPMENT_TEAM \
                     PRODUCT_BUNDLE_IDENTIFIER=$BUNDLE_ID \
                     CODE_SIGN_STYLE=Automatic \
                     clean archive || exit 1
          cd ../..
          echo "✅ Archive complete"

      - name: 📦 Export IPA
        script: |
          echo "📦 Exporting .ipa..."
          cd ios/App
          xcodebuild -exportArchive \
                     -archivePath ../build/App.xcarchive \
                     -exportPath ../build \
                     -exportOptionsPlist <(cat <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key><string>app-store</string>
            <key>signingStyle</key><string>automatic</string>
            <key>uploadSymbols</key><true/>
            <key>uploadBitcode</key><false/>
          </dict>
          </plist>
          EOF
          )
          cd ../..
          echo "✅ Export complete"

    artifacts:
      - ios/build/**/*.ipa
      - ios/build/App.xcarchive/**/*

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - Internal Testers
