workflows:
  ios-build:
    name: Build iOS for TestFlight
    max_build_duration: 60

    integrations:
      app_store_connect: mykey  # имя интеграции из Codemagic

    environment:
      node: 20.11.1
      xcode: latest
      cocoapods: default
      vars:
        APP_NAME: "VesselApp"
        DEVELOPMENT_TEAM: "AJ5RPURRUV"
        BUNDLE_ID: "vesseldatabase.app"
        CODE_SIGN_IDENTITY: "Apple Distribution"
        PROVISIONING_PROFILE_SPECIFIER: "mykey"

    scripts:
      - name: Install dependencies
        script: |
          echo "📦 Installing npm dependencies..."
          npm ci

          echo "📦 Installing Capacitor iOS platform..."
          npm install @capacitor/ios --force

          echo "🔧 Syncing iOS platform..."
          npx cap sync ios

          echo "📁 Installing CocoaPods dependencies..."
          cd ios/App
          pod install
          cd ../..

      - name: Build and export .ipa
        script: |
          echo "🚀 Building iOS release..."
          cd ios/App
          mkdir -p ../build

          # Очистка DerivedData
          rm -rf ~/Library/Developer/Xcode/DerivedData

          # 🏗️ Архивация
          xcodebuild -workspace App.xcworkspace \
                     -scheme App \
                     -sdk iphoneos \
                     -configuration Release \
                     -archivePath ../build/App.xcarchive \
                     DEVELOPMENT_TEAM=$DEVELOPMENT_TEAM \
                     PRODUCT_BUNDLE_IDENTIFIER=$BUNDLE_ID \
                     CODE_SIGN_STYLE=Manual \
                     CODE_SIGN_IDENTITY="$CODE_SIGN_IDENTITY" \
                     PROVISIONING_PROFILE_SPECIFIER="$PROVISIONING_PROFILE_SPECIFIER" \
                     -allowProvisioningUpdates \
                     clean archive || exit 1

          # 📦 Экспорт ipa для TestFlight
          cat > ExportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>app-store</string>
            <key>teamID</key>
            <string>$DEVELOPMENT_TEAM</string>
            <key>uploadBitcode</key>
            <false/>
            <key>compileBitcode</key>
            <true/>
            <key>signingStyle</key>
            <string>manual</string>
            <key>provisioningProfiles</key>
            <dict>
              <key>$BUNDLE_ID</key>
              <string>$PROVISIONING_PROFILE_SPECIFIER</string>
            </dict>
          </dict>
          </plist>
          EOF

          xcodebuild -exportArchive \
                     -archivePath ../build/App.xcarchive \
                     -exportPath ../build \
                     -exportOptionsPlist ExportOptions.plist \
                     -allowProvisioningUpdates || exit 1

          cd ../..
          echo "✅ Build complete"

    artifacts:
      - ios/build/**/*.ipa
      - ios/App/build/**/*.ipa
      - ios/build/App.xcarchive/**/*

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
