workflows:
  ios-build:
    name: Build iOS for TestFlight
    max_build_duration: 60

    integrations:
      app_store_connect: mykey

    environment:
      node: 20.11.1
      xcode: latest
      cocoapods: default
      vars:
        DEVELOPMENT_TEAM: "AJ5RPURRUV"
        BUNDLE_ID: "vesseldatabase.app"

    scripts:
      - name: Install dependencies
        script: |
          echo "📦 Installing dependencies..."
          npm ci
          npm install @capacitor/ios --force
          npx cap sync ios
          cd ios/App && pod install && cd ../..

      # 1️⃣ Получаем подписывающие файлы из App Store Connect
      - name: Fetch signing files from App Store Connect
        script: |
          echo "🔑 Fetching provisioning profiles and certificates..."
          app-store-connect fetch-signing-files "vesseldatabase.app" \
            --type IOS_APP_STORE \
            --team-id "AJ5RPURRUV" \
            --create

      # 2️⃣ Устанавливаем сертификаты и provisioning profiles
      - name: Install signing assets on build agent
        script: |
          echo "🔧 Installing certificates and profiles..."
          keychain initialize
          keychain add-certificates
          profiles install
          echo "✅ Certificates and provisioning profiles installed"

      # 3️⃣ Привязываем профиль только к таргету App
      - name: Bind provisioning profile to target App
        script: |
          echo "📘 Binding provisioning profile to App target..."
          xcode-project use-profiles \
            --project "ios/App/App.xcodeproj" \
            --target "App" \
            --bundle-id "vesseldatabase.app" \
            --export-method "app-store"
          echo "✅ Bound to App target only (Pods remain automatic)."

      # 4️⃣ Архивирование без ручных override переменных
      - name: Build (archive)
        script: |
          echo "🚀 Archiving app..."
          cd ios/App
          rm -rf ~/Library/Developer/Xcode/DerivedData
          xcodebuild -workspace App.xcworkspace \
                     -scheme App \
                     -sdk iphoneos \
                     -configuration Release \
                     -archivePath ../build/App.xcarchive \
                     DEVELOPMENT_TEAM=$DEVELOPMENT_TEAM \
                     PRODUCT_BUNDLE_IDENTIFIER=$BUNDLE_ID \
                     -allowProvisioningUpdates \
                     clean archive || exit 1

      # 5️⃣ Экспорт IPA с корректным профилем
      - name: Export .ipa (app-store)
        script: |
          echo "📦 Exporting .ipa..."
          cd ios/App
          cat > ExportOptions.plist <<'PLIST'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key><string>app-store</string>
            <key>signingStyle</key><string>manual</string>
            <key>provisioningProfiles</key>
            <dict>
              <key>vesseldatabase.app</key><string>VesselApp_Distribution</string>
            </dict>
          </dict>
          </plist>
          PLIST

          xcodebuild -exportArchive \
                     -archivePath ../build/App.xcarchive \
                     -exportPath ../build \
                     -exportOptionsPlist ExportOptions.plist \
                     -allowProvisioningUpdates || exit 1

          cd ../..
          echo "✅ Export complete"

    artifacts:
      - ios/build/**/*.ipa
      - ios/build/App.xcarchive/**/*

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
