workflows:
  ios-build:
    name: Build iOS for TestFlight
    max_build_duration: 60

    integrations:
      app_store_connect: mykey

    environment:
      node: 20.11.1
      xcode: latest
      cocoapods: default
      vars:
        DEVELOPMENT_TEAM: "AJ5RPURRUV"
        BUNDLE_ID: "vesseldatabase.app"

    scripts:
      - name: Install deps
        script: |
          npm ci
          npm install @capacitor/ios --force
          npx cap sync ios
          cd ios/App && pod install && cd ../..

      - name: Install signing assets (certs + profiles) and bind to target App
        script: |
          # Загрузить сертификат из Codemagic UI в системный кейчейн билдера
          keychain initialize
          keychain add-certificates

          # Подхватить загруженные в Codemagic provisioning profiles
          # и ПРОПИСАТЬ их в проект для таргета App (Pods не трогаем)
          xcode-project use-profiles \
            --project "ios/App/App.xcodeproj" \
            --target "App"

          echo "✓ Signing set for target 'App' only. Pods remain Automatic."

      - name: Build (no per-target overrides!)
        script: |
          cd ios/App
          rm -rf ~/Library/Developer/Xcode/DerivedData
          xcodebuild -workspace App.xcworkspace \
                     -scheme App \
                     -sdk iphoneos \
                     -configuration Release \
                     -archivePath ../build/App.xcarchive \
                     DEVELOPMENT_TEAM=$DEVELOPMENT_TEAM \
                     PRODUCT_BUNDLE_IDENTIFIER=$BUNDLE_ID \
                     -allowProvisioningUpdates \
                     clean archive || exit 1

          # Экспорт (используем provisioningProfiles в ExportOptions, а не через PROVISIONING_PROFILE_SPECIFIER)
          cat > ExportOptions.plist <<'PLIST'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key><string>app-store</string>
            <key>signingStyle</key><string>manual</string>
            <key>provisioningProfiles</key>
            <dict>
              <key>vesseldatabase.app</key><string>VesselApp_Distribution</string>
            </dict>
          </dict>
          </plist>
          PLIST

          xcodebuild -exportArchive \
                     -archivePath ../build/App.xcarchive \
                     -exportPath ../build \
                     -exportOptionsPlist ExportOptions.plist \
                     -allowProvisioningUpdates || exit 1
          cd ../..

    artifacts:
      - ios/build/**/*.ipa
      - ios/build/App.xcarchive/**/*
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
