workflows:
  ios-build:
    name: Build iOS for TestFlight
    max_build_duration: 60

    environment:
      node: 20.11.1
      xcode: latest
      cocoapods: default
      vars:
        APP_NAME: "VesselApp"
        APP_STORE_CONNECT_ISSUER_ID: Environ("APP_STORE_CONNECT_ISSUER_ID")
        APP_STORE_CONNECT_KEY_IDENTIFIER: Environ("APP_STORE_CONNECT_KEY_IDENTIFIER")
        APP_STORE_CONNECT_PRIVATE_KEY: Environ("APP_STORE_CONNECT_PRIVATE_KEY")

    scripts:
      - name: Install dependencies
        script: |
          echo "📦 Installing npm dependencies..."
          npm ci

          echo "📦 Installing Capacitor iOS platform..."
          npm install @capacitor/ios --force

          echo "🔧 Syncing iOS platform..."
          npx cap sync ios

          echo "📁 Installing CocoaPods dependencies..."
          cd ios/App
          pod install
          cd ../..

      - name: Build and export .ipa manually
        script: |
          echo "🚀 Building iOS release..."
          cd ios/App

          ARCHIVE_PATH="../build/App.xcarchive"
          EXPORT_PATH="../build/ipa"

          mkdir -p $EXPORT_PATH

          # 1️⃣ Архивируем
          xcodebuild -workspace App.xcworkspace \
                     -scheme App \
                     -sdk iphoneos \
                     -configuration Release \
                     -archivePath $ARCHIVE_PATH \
                     clean archive || exit 1

          # 2️⃣ Экспортируем ipa (если ExportOptions.plist есть — используем, если нет — создаём временный)
          if [ ! -f "ExportOptions.plist" ]; then
            echo "Creating temporary ExportOptions.plist"
            cat > ExportOptions.plist <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" 
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>method</key>
  <string>app-store</string>
  <key>uploadSymbols</key>
  <true/>
  <key>compileBitcode</key>
  <false/>
</dict>
</plist>
EOF
          fi

          xcodebuild -exportArchive \
                     -archivePath $ARCHIVE_PATH \
                     -exportPath $EXPORT_PATH \
                     -exportOptionsPlist ExportOptions.plist || true

          echo "📦 Contents of export path:"
          ls -la $EXPORT_PATH

          cd ../..

    artifacts:
      - ios/build/ipa/*.ipa
      - ios/App/build/**/*.app
      - ios/build/App.xcarchive/**/*

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
