workflows:
  ios-build:
    name: Build iOS for TestFlight
    max_build_duration: 60

    integrations:
      app_store_connect: mykey

    environment:
      node: 20.11.1
      xcode: latest
      cocoapods: default
      vars:
        DEVELOPMENT_TEAM: "AJ5RPURRUV"
        BUNDLE_ID: "vesseldatabase.app"

    scripts:
      # 1️⃣ Установка зависимостей
      - name: Install dependencies
        script: |
          echo "📦 Installing dependencies..."
          npm ci
          npm install @capacitor/ios --force
          npx cap sync ios
          cd ios/App && pod install && cd ../..
          echo "✅ Dependencies installed"

      # 2️⃣ Получаем provisioning profiles и сертификаты из App Store Connect
      - name: Fetch signing files from App Store Connect
        script: |
          echo "🔑 Fetching provisioning profiles and certificates..."
          app-store-connect fetch-signing-files "vesseldatabase.app" \
            --type IOS_APP_STORE \
            --create \
            --verbose
          echo "✅ Signing files fetched successfully"

      # 3️⃣ Устанавливаем сертификаты и provisioning profiles на билд-агенте
      - name: Install signing assets
        script: |
          echo "🔧 Installing certificates and provisioning profiles..."
          keychain initialize
          keychain add-certificates
          profiles install
          echo "✅ Certificates and profiles installed"

      # 4️⃣ Привязываем профиль только к таргету App
      - name: Bind provisioning profile to App target
        script: |
          echo "📘 Binding provisioning profile to App target..."
          xcode-project use-profiles \
            --project "ios/App/App.xcodeproj" \
            --target "App" \
            --bundle-id "vesseldatabase.app" \
            --export-method "app-store"
          echo "✅ Bound provisioning profile to App target (Pods remain Automatic)."

      # 5️⃣ Архивирование проекта (без ручных overrides)
      - name: Build (archive)
        script: |
          echo "🚀 Archiving app..."
          cd ios/App
          rm -rf ~/Library/Developer/Xcode/DerivedData
          xcodebuild -workspace App.xcworkspace \
                     -scheme App \
                     -sdk iphoneos \
                     -configuration Release \
                     -archivePath ../build/App.xcarchive \
                     DEVELOPMENT_TEAM=$DEVELOPMENT_TEAM \
                     PRODUCT_BUNDLE_IDENTIFIER=$BUNDLE_ID \
                     -allowProvisioningUpdates \
                     clean archive || exit 1
          cd ../..
          echo "✅ Archive completed successfully"

      # 6️⃣ Экспорт IPA с правильным профилем
      - name: Export .ipa (App Store)
        script: |
          echo "📦 Exporting .ipa..."
          cd ios/App

          cat > ExportOptions.plist <<'PLIST'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key><string>app-store</string>
            <key>signingStyle</key><string>manual</string>
            <key>provisioningProfiles</key>
            <dict>
              <key>vesseldatabase.app</key><string>VesselApp_Distribution</string>
            </dict>
          </dict>
          </plist>
          PLIST

          xcodebuild -exportArchive \
                     -archivePath ../build/App.xcarchive \
                     -exportPath ../build \
                     -exportOptionsPlist ExportOptions.plist \
                     -allowProvisioningUpdates || exit 1

          cd ../..
          echo "✅ .ipa export completed successfully"

    artifacts:
      - ios/build/**/*.ipa
      - ios/build/App.xcarchive/**/*

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
