workflows:
  ios-build:
    name: Build iOS for TestFlight
    max_build_duration: 60
    environment:
      vars:
        APP_NAME: "VesselApp"
        BUNDLE_ID: "vesseldatabase.app"
        APPLE_TEAM_ID: "AJ5RPURRUV"
        APP_STORE_CONNECT_KEY_IDENTIFIER: "B6FY374P4S"
        APP_STORE_CONNECT_ISSUER_ID: "61b8c759-faf7-4d66-ae16-112010c41c81"
        APP_STORE_CONNECT_PRIVATE_KEY: Encrypted("your_base64_private_key_here") # не нужно вручную, Codemagic сам подставит из интеграции
      node: 20.11.1
      xcode: latest
      cocoapods: default

    integrations:
      app_store_connect: mykey

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "main"
          include: true
          source: true

    scripts:
      - name: 🔧 Install dependencies
        script: |
          npm install
          npm run build
          npx cap sync ios

      - name: 🧱 Build iOS app
        script: |
          cd ios/App
          xcodebuild \
            -workspace App.xcworkspace \
            -scheme App \
            -sdk iphoneos \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/build/App.xcarchive \
            DEVELOPMENT_TEAM=$APPLE_TEAM_ID \
            PRODUCT_BUNDLE_IDENTIFIER=$BUNDLE_ID \
            CODE_SIGN_STYLE=Manual \
            CODE_SIGN_IDENTITY="Apple Distribution" \
            clean archive

      - name: 📦 Export IPA
        script: |
          xcodebuild \
            -exportArchive \
            -archivePath $CM_BUILD_DIR/build/App.xcarchive \
            -exportOptionsPlist ios/App/exportOptions.plist \
            -exportPath $CM_BUILD_DIR/build/ipa

    artifacts:
      - build/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - Internal Testers
