workflows:
  ios-build:
    name: Build iOS for TestFlight
    max_build_duration: 60

    integrations:
      app_store_connect: mykey

    environment:
      node: 20.11.1
      xcode: latest
      cocoapods: default
      vars:
        DEVELOPMENT_TEAM: "AJ5RPURRUV"
        BUNDLE_ID: "vesseldatabase.app"
        PROFILE_NAME: "VesselApp_Distribution"

    scripts:
      - name: Install dependencies
        script: |
          echo "📦 Installing dependencies..."
          npm ci
          npm install @capacitor/ios --force
          npx cap sync ios
          cd ios/App && pod install && cd ../..
          echo "✅ Dependencies installed"

      - name: Fetch signing files
        script: |
          echo "🔑 Fetching provisioning profiles and certificates..."
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create --verbose
          echo "✅ Signing files fetched"

      - name: Install signing assets
        script: |
          echo "🔧 Installing certificates and provisioning profiles..."
          keychain initialize
          keychain add-certificates
          profiles install
          echo "✅ Installed certificates and profiles"

      - name: Bind provisioning profile only to App target
        script: |
          echo "📘 Binding provisioning profile to App target..."
          # Только App, Pods остаются Automatic
          xcode-project use-profiles \
            --project "ios/App/App.xcodeproj" \
            --target "App" \
            --bundle-id "$BUNDLE_ID" \
            --export-method "app-store"
          echo "✅ Bound only to App target (Pods unchanged)."

      - name: Build (archive)
        script: |
          echo "🚀 Archiving app..."
          cd ios/App
          rm -rf ~/Library/Developer/Xcode/DerivedData

          xcodebuild -workspace App.xcworkspace \
                     -scheme App \
                     -sdk iphoneos \
                     -configuration Release \
                     -archivePath ../build/App.xcarchive \
                     DEVELOPMENT_TEAM=$DEVELOPMENT_TEAM \
                     PRODUCT_BUNDLE_IDENTIFIER=$BUNDLE_ID \
                     CODE_SIGN_STYLE=Manual \
                     CODE_SIGN_IDENTITY="Apple Distribution" \
                     -allowProvisioningUpdates \
                     clean archive || exit 1
          cd ../..
          echo "✅ Archive completed"

      - name: Export .ipa
        script: |
          echo "📦 Exporting .ipa..."
          cd ios/App
          cat > ExportOptions.plist <<'PLIST'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key><string>app-store</string>
            <key>signingStyle</key><string>manual</string>
            <key>provisioningProfiles</key>
            <dict>
              <key>vesseldatabase.app</key><string>VesselApp_Distribution</string>
            </dict>
            <key>uploadSymbols</key><true/>
            <key>uploadBitcode</key><false/>
          </dict>
          </plist>
          PLIST

          xcodebuild -exportArchive \
                     -archivePath ../build/App.xcarchive \
                     -exportPath ../build \
                     -exportOptionsPlist ExportOptions.plist \
                     -allowProvisioningUpdates || exit 1
          cd ../..
          echo "✅ .ipa exported successfully"

    artifacts:
      - ios/build/**/*.ipa
      - ios/build/App.xcarchive/**/*

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
